apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: world-viewer
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: test-binding-world
spec:
  subjects:
  - properties:
      source.namespace: "hello"
  roleRef:
    kind: ServiceRole
    name: "world-viewer"

