apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hello-default
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: hello
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hello-foo
spec:
  destination:
    name: hello
  precedence: 2
  match:
    request:
      headers:
        Foo: bar
  route:
  - labels:
      version: v2
---
