apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hello-earth
spec:
  destination:
    name: world
  precedence: 1
  httpFault:
    delay:
      fixedDelay: 7.000s
      percent: 10
    abort:
      httpStatus: 500
      percent: 10
  match:
    source:
      name: hello
      labels: 
        version: v1
  route:
  - labels:
      version: v1
    weight: 50
  - labels:
      version: v2
    weight: 50
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: morning-world
spec:
  destination:
    name: world
  precedence: 2
  match:
    source:
      name: hello
      labels: 
        version: v2
  route:
  - labels:
      version: v1
