apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hello-morning
spec:
  destination:
    name: hello
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: ^(.*?;)?(user=jason)(;.*)?$
  route:
  - labels:
      version: v2
